FROM node:16-alpine
 
USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
 
CMD ["npm", "start"]
#img d10d34c0e7d9bf44d
#sudo docker run -p 3000:3000 -v home/node/app/node_modules -v ~/my-app:/home/node/app d10d34c0e7d9bf44d
